/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/d3_move.h,v $
  SHORTNAME      : move.h
  SNNS VERSION   : 4.2

  PURPOSE        : header for d3_move.c
  NOTES          : all functions will be exported

  AUTHOR         : Ralf Huebner
  DATE           : 1.12.1991

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:20:29 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _D3_MOVE_DEFINED_
#define _D3_MOVE_DEFINED_


extern void d3_createMovePannel (Widget parent);


#endif /* _D3_MOVE_DEFINED_ */


/* end of file */
/* lines: 24 */

/* 41 lines generated by deleteprivatedefinitions.awk */
