/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/d3_main.h,v $
  SHORTNAME      : main.h
  SNNS VERSION   : 4.2

  PURPOSE        : header for d3_main.c
  NOTES          : all functions will be exported 

  AUTHOR         : Ralf Huebner
  DATE           : 1.12.1991

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:20:24 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _D3_MAIN_DEFINED_
#define _D3_MAIN_DEFINED_




#define CENTER_VECTOR 8


extern void d3_getColorValue (int mode, int unitNo, float *value);
extern void d3_drawNet (void);
extern void d3_recenter_window (int width, int height);
extern void d3_resetDisplay (void);
extern void d3_clear_xyTranslationTable (void);
extern void d3_init_main (void);






#endif /* _D3_MAIN_DEFINED_ */


/* end of file */
/* lines: 29 */

/* 49 lines generated by deleteprivatedefinitions.awk */
