/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/d3_point.h,v $
  SHORTNAME      : point.h
  SNNS VERSION   : 4.2

  PURPOSE        : header for d3_point.c
  NOTES          : all functions will be exported

  AUTHOR         : Ralf Huebner
  DATE           : 1.12.1991

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:20:34 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _D3_POINT_DEFINED_
#define _D3_POINT_DEFINED_




#define POINT_BLOCK_SIZE  1024


extern void d3_putPixel (int, int);
extern void d3_putColPixel (int, int);
extern void d3_flushPixels (void);






#endif /* _D3_POINT_DEFINED_ */


/* end of file */
/* lines: 26 */

/* 46 lines generated by deleteprivatedefinitions.awk */
