/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/d3_shade.h,v $
  SHORTNAME      : shade.ph
  SNNS VERSION   : 4.2

  PURPOSE        : header for d3_shade.h
  NOTES          : all functions will be exported

  AUTHOR         : Ralf Huebner
  DATE           : 1.12.1991

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:20:42 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _D3_SHADE_DEFINED_
#define _D3_SHADE_DEFINED_




extern void d3_shadeIntens (float *intens, float *v1, float *normal, float *lp);



#endif /* _D3_SHADE_DEFINED_ */


/* end of file */
/* lines: 22 */

/* 44 lines generated by deleteprivatedefinitions.awk */
