/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/d3_units.h,v $
  SHORTNAME      : units.ph
  SNNS VERSION   : 4.2

  PURPOSE        : header for d3_units.c
  NOTES          : all functions will be exported

  AUTHOR         : Ralf Huebner
  DATE           : 1.12.1991

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:20:45 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _D3_UNITS_DEFINED_
#define _D3_UNITS_DEFINED_




extern void d3_createUnitPannel (Widget w, Widget button, caddr_t call_data);





#endif /* _D3_UNITS_DEFINED_ */


/* end of file */
/* lines: 24 */

/* 44 lines generated by deleteprivatedefinitions.awk */
