/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/d3_zgraph.h,v $
  SHORTNAME      : zgraph.ph
  SNNS VERSION   : 4.2

  PURPOSE        : header for d3_zgraph.c
  NOTES          : all functions will be exported

  AUTHOR         : Ralf Huebner
  DATE           : 1.12.1991

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:20:52 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _D3_ZGRAPH_DEFINED_
#define _D3_ZGRAPH_DEFINED_




extern int d3_initZbuffer (void);
extern void d3_clearZbuffer (void);
extern void d3_readZbuffer (int, int, float *);
extern void d3_writeZbuffer (int, int, float);
extern void d3_freeZbuffer (void);




#endif /* _D3_ZGRAPH_DEFINED_ */


/* end of file */
/* lines: 30 */

/* 49 lines generated by deleteprivatedefinitions.awk */
