/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_control.h,v $
  SHORTNAME      : control.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Tilman Sommer
  DATE           : 20.7.1990

  CHANGED BY     : Michael Vogt, Guenter Mamier
  RCS VERSION    : $Revision: 1.9 $ 
  LAST CHANGE    : $Date: 1998/02/25 15:21:24 $  

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _UI_CONTROL_DEFINED_
#define _UI_CONTROL_DEFINED_




extern void  ui_xCreateControlPanel(Widget parent);
extern void  ui_NumberOfLearnParamsChanged(void);
extern void  ui_NumberOfUpdateParamsChanged(void);
extern void  ui_NumberOfInitParamsChanged(void);
extern void  ui_NumberOfRemapParamsChanged(void);


/* shell widget of control panel */
extern Widget    ui_controlPanel;
/* ascii and label widgets containing/displaying data */
extern Widget    ui_numberOfStepsWidget, ui_numberOfStepsDoneWidget;
extern Widget    ui_numberOfCyclesWidget, ui_numberOfPatternWidget;
extern Widget    ui_showModeLabel;
extern Widget    ui_showTestPattFile; 
extern Widget    ui_showPattFile;
extern Widget    REM_UFileMenu;
extern Widget    REM_UTestFileMenu; 
extern Widget    REM_DFileMenu;
extern Widget    in_dim_widgets[];
extern Widget    out_dim_widgets[];
extern Widget    subIPatSizeW[];
extern Widget    subIPatPosW[];
extern Widget    subIPatStepW[];
extern Widget    subOPatStepW[];
extern Widget    subOPatSizeW[];
extern Widget    subOPatPosW[];
extern Widget    DELPattFileWidget[];
extern Widget    USEPattFileWidget[];
extern Widget    USETestPattFileWidget[];  
extern Widget    ui_learnParameterWidgets[];
extern Widget    ui_updateParameterWidgets[];
extern Widget    ui_initParameterWidgets[];
extern Widget    ui_remapParameterWidgets[];
extern Widget    ui_subPatternWidgets[];
extern Widget    ui_testFrequencyWidget;
extern Widget    jogbutton;

/* current configuration of control panel */
extern int       ui_noOfCurrentPattern;  /* number of current pattern
                                         0 means, no patterns loaded */
extern int       ui_patternLoadMode;
extern int       ui_numberOfStepsDone;
extern int       SubPatPanel;
extern float     ui_learnParameters[];
extern int       subIPatSize[];
extern int       subIPatPos[];
extern int       subIPatStep[];
extern int       subOPatStep[];
extern int       subOPatSize[];
extern int       subOPatPos[];
extern int       subIPatNo;
extern int       subIPatDims;
extern int       subOPatDims;
extern float     ui_updateParameters[];
extern float     ui_initParameters[];
extern float     ui_remapParameters[];
extern Bool      ui_shuffleFlg;
extern Bool      ui_jogFlg;
extern Bool      ui_jogCorrFlg;
extern float     jog_low, jog_high, jog_correlation;
extern Bool      ui_shuffleSubPatFlg;
extern Bool      ui_controlIsCreated;

extern int       ui_numberOfCycles;
extern int       ui_numberOfSteps;
extern int       ui_testFrequency;
#endif /* _UI_CONTROL_DEFINED_ */


/* end of file */
/* lines: 25 */

/* 64 lines generated by deleteprivatedefinitions.awk */
