/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_display.h,v $
  SHORTNAME      : display.h
  SNNS VERSION   : 4.2

  PURPOSE  	 : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR   	 : Tilman Sommer
  DATE           : 1.2.1990

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:21:31 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG

******************************************************************************/


#ifndef _UI_DISPLAY_DEFINED_
#define _UI_DISPLAY_DEFINED_




extern struct Ui_DisplayType *ui_currentDisplay;  /* current display */
extern struct Ui_DisplayType *ui_displ_listPtr;   /* pointer to first item */

extern int      ui_displ_numberOfItems;       /* number of created items */


extern void             ui_displ_initDisplayList(void);
extern void             ui_displ_freeItem(struct Ui_DisplayType *displayPtr);
	/* free it */
extern void             ui_displ_resetList(void);     /* free al items */
extern struct Ui_DisplayType  *ui_displ_getFreeItem(void);   /* create */
extern Bool             ui_displ_isSomeWhereToShowWeights(void);
extern Bool             ui_displ_isSomeWhereToShowValues(void);
extern void             ui_displ_freezeDisplay(Widget w, 
                                struct Ui_DisplayType *displayPtr, 
                                caddr_t call_data);



#endif /* _UI_DISPLAY_DEFINED_ */



/* end of file */
/* lines: 34 */

/* 57 lines generated by deleteprivatedefinitions.awk */
