/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_displwght.h,v $
  SHORTNAME      : ui_displweights
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Guenter Mamier 
  DATE           : 14.01.92 

  CHANGED BY     : Sven Doering
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:21:36 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG

******************************************************************************/

#ifndef _UI_DISPLWGHT_DEFINED_
#define _UI_DISPLWGHT_DEFINED_

extern void         ui_displWeights(Widget w, caddr_t call_data);
extern void         ui_displWeightsFromUpdate(void);



#endif




/* 34 lines generated by deleteprivatedefinitions.awk */
