/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_info.h,v $
  SHORTNAME      : info.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Tilman Sommer
  DATE           : 11.5.1990

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:21:54 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
******************************************************************************/


#ifndef _UI_INFO_DEFINED_
#define _UI_INFO_DEFINED_




extern void ui_xCreateInfoPanel(Widget parent);
	/* the parent widget of the new form widget */

extern struct UnitAttributeType  ui_sourceUnit, ui_targetUnit;
	/* attributes of source/target unit in the info panel */






#endif /* _UI_INFO_DEFINED_ */







/* end of file */
/* lines: 37 */

/* 49 lines generated by deleteprivatedefinitions.awk */
