/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_inversion.h,v $
  SHORTNAME      : inversion.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Guenter Mamier 
  DATE           : 29.01.92

  CHANGED BY     : Sven Doering
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:00 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG

******************************************************************************/

#ifndef _UI_INVERSION_DEFINED_
#define _UI_INVERSION_DEFINED_


extern void ui_inversion(Widget button, caddr_t call_data);

extern int      INVERS_CREATED;       /* TRUE if display exists      */
extern Widget   ui_InvRootWidget;     /* root widget for inversion   */

#endif

/* 32 lines generated by deleteprivatedefinitions.awk */
