/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_key.h,v $
  SHORTNAME      : key.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Tilman Sommer
  DATE           : 6.6.1990

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.8 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:02 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _UI_KEY_DEFINED_
#define _UI_KEY_DEFINED_




extern void ui_key_popMenu (struct Ui_DisplayType *displayPtr);
extern void ui_key_init (void);
extern void ui_can_KEventProc (Widget w, struct Ui_DisplayType *displayPtr, 
				XEvent *event);
extern void ui_key_control(Widget w, Cardinal n, XEvent *event);

extern StateType  ui_key_currentState,
    	ui_key_returnUnitState;  /* dito from state UNIT */

extern struct PosType  ui_key_eventPos;     /* position of current event */
extern int             ui_key_unitNo;    /* unit at this position, else ZERO */
				/* current key event */
extern Bool              ui_safetyFlg; /* safety on of off */
extern FlagType          ui_key_linksToHandle; /* which links are to handle:
                                           UI_ALL (input and output)
                                           UI_INPUT UI_OUTPUT UI_NONE */
extern FlagType          ui_key_action; /* used for MOVE and COPY to tell the
                                    mouse event handler the selected action */

extern Bool            ui_outlineActive; /* waiting for a 
						destination position */




#endif /* _UI_KEY_DEFINED_ */


/* end of file */
/* lines: 28 */

/* 60 lines generated by deleteprivatedefinitions.awk */
