/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_maspar.h,v $
  SHORTNAME      : maspar.h
  SNNS VERSION   : 4.2

  PURPOSE        :
  NOTES          :

  AUTHOR         :
  DATE           :

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:22 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG

******************************************************************************/


#ifdef MASPAR_KERNEL


#ifndef _UI_MASPAR_DEFINED_
#define _UI_MASPAR_DEFINED_




extern void ui_masparPannel (Widget, Widget, caddr_t);






#endif /* _UI_MASPAR_DEFINED_ */


#endif /* MASPAR_KERNEL */


/* end of file */
/* lines: 9 */

/* 47 lines generated by deleteprivatedefinitions.awk */
