/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_netUpdate.h,v $
  SHORTNAME      : netUpdat.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Tilman Sommer
  DATE           : 18.5.1990

  CHANGED BY     : Guenter Mamier
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:28 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _UI_NETUPDATE_DEFINED_
#define _UI_NETUPDATE_DEFINED_

extern void ui_net_drawLink (struct Ui_DisplayType *, FlagType, int, int, 
			     FlintType, Bool);
extern void ui_net_drawUnit (struct Ui_DisplayType *, FlagType, int, Bool);
extern void ui_net_drawAllLinksToUnit (struct Ui_DisplayType *, FlagType, 
				       int, Bool);
extern void ui_net_drawAllLinksFromUnit (struct Ui_DisplayType *, FlagType, 
					 int, FlagType);
extern void ui_net_updateWhole (struct Ui_DisplayType *, FlagType, int, Bool);
extern void ui_net_completeRefresh (struct Ui_DisplayType *, FlagType);

#endif /* _UI_NETUPDATE_DEFINED_ */


/* end of file */
/* lines: 30 */

/* 57 lines generated by deleteprivatedefinitions.awk */
