/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_status.h,v $
  SHORTNAME      : status.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Tilman Sommer
  DATE           : 1.2.1990

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:44 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _UI_STATUS_DEFINED_
#define _UI_STATUS_DEFINED_




extern void ui_stat_displayStatus(struct PosType gridPos);






#endif /* _UI_STATUS_DEFINED_ */


/* end of file */
/* lines: 28 */

/* 41 lines generated by deleteprivatedefinitions.awk */
