/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_selection.h,v $
  SHORTNAME      : select.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :

  AUTHOR         : Tilman Sommer
  DATE           : 29.5.1990

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:36 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _UI_SELECTION_DEFINED_
#define _UI_SELECTION_DEFINED_




extern void ui_sel_msgNumber (void);
extern void ui_sel_initSelectionList (void);
extern struct SelectionType *ui_sel_lookForItem (int unitNo);
extern struct SelectionType *ui_sel_lookForSelectedItem 
					(struct SelectionType *);
extern void ui_sel_drawBoxes (struct Ui_DisplayType *,FlagType,struct PosType);
extern void ui_sel_selectOne (struct Ui_DisplayType *, FlagType, int, 
					struct PosType);
extern void ui_sel_unselectOne (struct Ui_DisplayType *, FlagType, int, 
					struct PosType);
extern void ui_sel_selectRect (struct Ui_DisplayType *, FlagType, 
					struct PosType, struct PosType);
extern void ui_sel_unselectRect (struct Ui_DisplayType *, FlagType, 
					struct PosType, struct PosType);
extern void ui_sel_reshowItems (struct Ui_DisplayType *, FlagType);
extern void ui_sel_checkList (struct Ui_DisplayType *, FlagType);
extern void ui_sel_unselectAll (struct Ui_DisplayType *, FlagType);
extern void ui_sel_resetList (void);


/* handling of the selection list */
extern struct SelectionType  *ui_sel_listPtr;        /* pointer to first item */
extern int            ui_sel_numberOfSelectedItems;  /* number of selected items */



#endif /* _UI_SELECTION_DEFINED_ */


/* end of file */
/* lines: 46 */

/* 62 lines generated by deleteprivatedefinitions.awk */
