/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/xgui/sources/ui_textP.h,v $
  SHORTNAME      : textP.h
  SNNS VERSION   : 4.2

  PURPOSE        : Header file of correspondent '.c' file
  NOTES          :


  AUTHOR         : Tilman Sommer
  DATE           : 23.7.1990

  CHANGED BY     :
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:22:47 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG
             
******************************************************************************/


#ifndef _UI_TEXTP_DEFINED_
#define _UI_TEXTP_DEFINED_




extern void  ui_tw_errorMessage(char *message);
extern void  ui_tw_printMessage(char *message);






#endif /* _UI_TEXTP_DEFINED_ */


/* end of file */
/* lines: 29 */

/* 43 lines generated by deleteprivatedefinitions.awk */
